services:
  backend:
    build:
      context: ./src/backend
    container_name: frame-inventory-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongodb:27017/frames?authSource=admin
    depends_on:
      - mongodb
    networks:
      - frame-inventory

  frontend:
    build:
      context: ./src/frontend
    container_name: frame-inventory-frontend
    ports:
      - "3000:3000"
    environment:
      VITE_BACKEND_URL: http://backend:8080
    volumes:
      - ./src/frontend/src:/app/src
      - ./src/frontend/public:/app/public
      - ./src/frontend/index.html:/app/index.html
    depends_on:
      - backend
    networks:
      - frame-inventory

  mongodb:
    image: mongo:7
    container_name: frame-inventory-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: frames
    volumes:
      - mongodb-data:/data/db
    networks:
      - frame-inventory


volumes:
  mongodb-data:

networks:
  frame-inventory:
    driver: bridge
